'use client'

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Link from 'next/link'

import { CircleUser, Menu, Package2 } from 'lucide-react'

import { ThemeProvider } from '@/components/atoms/theme-provider'

import '../../app/globals.css'
import { cn } from '@/lib/utils'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Telo App',
  description: 'Generated by create next app',
}

import InstallAppCard from '../molecules/install-app-card'
import { NextUIProvider } from '@nextui-org/react'

import { MENU_ROUTES } from '@/common/routes'

import { Button } from '@/components/atoms/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/atoms/dropdown-menu'
import { ModeToggle } from '@/components/atoms/mode-toggle'
import { Sheet, SheetContent, SheetTrigger } from '@/components/atoms/sheet'

import { useStoreButtomSheet } from '@/store/ButtonSheet.state'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { isSheetOpen, setIsSheetOpen } = useStoreButtomSheet()

  return (
    <html lang="en" suppressHydrationWarning>
      <title>Telo App</title>
      <meta name="description" content="App de ticket." />

      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width" />

      <meta name="keywords" content="Keywords" />

      <link rel="manifest" href="/manifest.json" />
      <link
        href="/icons/icon-16x16.png"
        rel="icon"
        type="image/png"
        sizes="16x16"
      />
      <link
        href="/icons/icon-32x32.png"
        rel="icon"
        type="image/png"
        sizes="32x32"
      />
      <link rel="apple-touch-icon" href="/icons/icon-72x72.png"></link>
      <meta name="theme-color" content="#6064FF" />

      <body
        className={cn(
          'min-h-screen bg-background antialiased',
          roboto.className,
        )}
      >
        <NextUIProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <div className="fixed grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
              <div className="hidden border-r bg-muted/40 md:block">
                <div className="flex h-full max-h-screen flex-col gap-2">
                  <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                    <Link
                      href="/"
                      className="flex items-center gap-2 font-semibold"
                    >
                      <Package2 className="size-6" />
                      <span>Telo App</span>
                    </Link>
                  </div>
                  <div className="flex-1">
                    <nav className="grid items-start px-2 text-sm font-medium lg:px-4">
                      {MENU_ROUTES.map(({ label, route, icon: Icon }, key) => (
                        <Link
                          key={key}
                          href={route}
                          className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
                        >
                          <Icon className="size-4 text-primary" />
                          <p className="text-lg text-primary">{label}</p>
                        </Link>
                      ))}
                    </nav>
                  </div>
                  <InstallAppCard />
                </div>
              </div>
              <div className="flex flex-col">
                <header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6">
                  <Sheet open={isSheetOpen} onOpenChange={setIsSheetOpen}>
                    <SheetTrigger asChild>
                      <Button
                        variant="outline"
                        size="icon"
                        className="shrink-0 md:hidden"
                      >
                        <Menu className="size-5" />
                        <span className="sr-only">Toggle navigation menu</span>
                      </Button>
                    </SheetTrigger>
                    <SheetContent side="left" className="flex flex-col">
                      <nav className="grid gap-2 text-lg font-medium">
                        <Link
                          href="#"
                          className="flex items-center gap-2 text-lg font-semibold"
                        >
                          <Package2 className="size-6" />
                          <span className="sr-only">Telo App</span>
                        </Link>
                        {MENU_ROUTES.map(
                          ({ label, route, icon: Icon }, key) => (
                            <Link
                              key={key}
                              href={route}
                              onClick={() => setIsSheetOpen(false)}
                              className="mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground"
                            >
                              <Icon className="size-5" />
                              <p className="text-lg">{label}</p>
                            </Link>
                          ),
                        )}
                      </nav>
                      <InstallAppCard />
                    </SheetContent>
                  </Sheet>
                  <div className="flex w-full justify-end gap-3">
                    <ModeToggle />
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button
                          variant="secondary"
                          size="icon"
                          className="rounded-full"
                        >
                          <CircleUser className="size-5" />
                          <span className="sr-only">Toggle user menu</span>
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuLabel>My Account</DropdownMenuLabel>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem>Settings</DropdownMenuItem>
                        <DropdownMenuItem>Support</DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem>Logout</DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </header>
                <main
                  className="flex h-auto flex-1 flex-col gap-4 overflow-y-auto p-4 lg:gap-6 lg:p-6"
                  style={{ maxHeight: 'calc(100vh - 60px)' }}
                >
                  {children}
                </main>
              </div>
            </div>
          </ThemeProvider>
        </NextUIProvider>
      </body>
    </html>
  )
}
